# Welcome to Jekyll!

lang: ja_JP
title: tk3++
description: >-
  tk3's memo

#twitter_username: tk3inc
#github_username: tk3

theme: minima
permalink: /posts/:year/:month/:day/:hour:minute:second
plugins:
  - jekyll-feed

